export const backgrounds = [
  {
    name: "colorBackgroundBody",
    value: "#F5F7F9",
    path: ["color", "background", "body"],
    attributes: {
      category: "color",
      type: "background",
      item: "body",
    },
  },
  {
    name: "colorBackgroundModal",
    value: "#FFFFFF",
    path: ["color", "background", "modal"],
    attributes: {
      category: "color",
      type: "background",
      item: "modal",
    },
  },
  {
    name: "colorBackgroundCard",
    value: "#FFFFFF",
    path: ["color", "background", "card"],
    attributes: {
      category: "color",
      type: "background",
      item: "card",
    },
  },
  {
    name: "colorBackgroundCarrierLogoDefault",
    value: "transparent",
    path: ["color", "background", "carrier", "logo", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "carrier",
      subitem: "logo",
      status: "default",
    },
  },
  {
    name: "colorBackgroundCountryFlagDefault",
    value: "transparent",
    path: ["color", "background", "country", "flag", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "country",
      subitem: "flag",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonPrimaryDefault",
    value: "#00A991",
    path: ["color", "background", "button", "primary", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "primary",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonPrimaryHover",
    value: "#009882",
    path: ["color", "background", "button", "primary", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "primary",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButtonPrimaryActive",
    value: "#008F7B",
    path: ["color", "background", "button", "primary", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "primary",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButtonSecondaryDefault",
    value: "#E8EDF1",
    path: ["color", "background", "button", "secondary", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "secondary",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonSecondaryHover",
    value: "#DCE3E9",
    path: ["color", "background", "button", "secondary", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "secondary",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButtonSecondaryActive",
    value: "#CAD4DE",
    path: ["color", "background", "button", "secondary", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "secondary",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButtonFacebookDefault",
    value: "#3B5998",
    path: ["color", "background", "button", "facebook", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "facebook",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonFacebookHover",
    value: "#385490",
    path: ["color", "background", "button", "facebook", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "facebook",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButtonFacebookActive",
    value: "#354F88",
    path: ["color", "background", "button", "facebook", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "facebook",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButtonGoogleDefault",
    value: "#F5F7F9",
    path: ["color", "background", "button", "google", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "google",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonGoogleHover",
    value: "#E5EAEF",
    path: ["color", "background", "button", "google", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "google",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButtonGoogleActive",
    value: "#D6DEE6",
    path: ["color", "background", "button", "google", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "google",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButtonInfoDefault",
    value: "#0172CB",
    path: ["color", "background", "button", "info", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "info",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonInfoHover",
    value: "#0161AC",
    path: ["color", "background", "button", "info", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "info",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButtonInfoActive",
    value: "#01508E",
    path: ["color", "background", "button", "info", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "info",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButtonSuccessDefault",
    value: "#28A138",
    path: ["color", "background", "button", "success", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "success",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonSuccessHover",
    value: "#238B31",
    path: ["color", "background", "button", "success", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "success",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButtonSuccessActive",
    value: "#1D7228",
    path: ["color", "background", "button", "success", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "success",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButtonWarningDefault",
    value: "#E98305",
    path: ["color", "background", "button", "warning", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "warning",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonWarningHover",
    value: "#DC7C05",
    path: ["color", "background", "button", "warning", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "warning",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButtonWarningActive",
    value: "#CD7304",
    path: ["color", "background", "button", "warning", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "warning",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButtonCriticalDefault",
    value: "#D21C1C",
    path: ["color", "background", "button", "critical", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "critical",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonCriticalHover",
    value: "#B91919",
    path: ["color", "background", "button", "critical", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "critical",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButtonCriticalActive",
    value: "#9D1515",
    path: ["color", "background", "button", "critical", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "critical",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButtonWhiteDefault",
    value: "#FFFFFF",
    path: ["color", "background", "button", "white", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "white",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonWhiteHover",
    value: "#F5F7F9",
    path: ["color", "background", "button", "white", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "white",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButtonWhiteActive",
    value: "#E5EAEF",
    path: ["color", "background", "button", "white", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "white",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButtonBorderedDefault",
    value: "transparent",
    path: ["color", "background", "button", "bordered", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "bordered",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonBorderedHover",
    value: "#F5F7F9",
    path: ["color", "background", "button", "bordered", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "bordered",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButtonBorderedActive",
    value: "#F5F7F9",
    path: ["color", "background", "button", "bordered", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "bordered",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButtonWhite-borderedDefault",
    value: "transparent",
    path: ["color", "background", "button", "white-bordered", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "white-bordered",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButtonWhite-borderedHover",
    value: "rgba(255, 255, 255, 0.2)",
    path: ["color", "background", "button", "white-bordered", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "white-bordered",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButtonWhite-borderedActive",
    value: "rgba(255, 255, 255, 0.2)",
    path: ["color", "background", "button", "white-bordered", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button",
      subitem: "white-bordered",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButton-linkPrimaryDefault",
    value: "transparent",
    path: ["color", "background", "button-link", "primary", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button-link",
      subitem: "primary",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButton-linkPrimaryHover",
    value: "#E5EAEF",
    path: ["color", "background", "button-link", "primary", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button-link",
      subitem: "primary",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButton-linkPrimaryActive",
    value: "#D6DEE6",
    path: ["color", "background", "button-link", "primary", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button-link",
      subitem: "primary",
      status: "active",
    },
  },
  {
    name: "colorBackgroundButton-linkSecondaryDefault",
    value: "transparent",
    path: ["color", "background", "button-link", "secondary", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "button-link",
      subitem: "secondary",
      status: "default",
    },
  },
  {
    name: "colorBackgroundButton-linkSecondaryHover",
    value: "#E5EAEF",
    path: ["color", "background", "button-link", "secondary", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "button-link",
      subitem: "secondary",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundButton-linkSecondaryActive",
    value: "#D6DEE6",
    path: ["color", "background", "button-link", "secondary", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "button-link",
      subitem: "secondary",
      status: "active",
    },
  },
  {
    name: "colorBackgroundInput",
    value: "#FFFFFF",
    path: ["color", "background", "input"],
    attributes: {
      category: "color",
      type: "background",
      item: "input",
    },
  },
  {
    name: "colorBackgroundInputDisabledDefault",
    value: "#EFF2F5",
    path: ["color", "background", "input", "disabled", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "input",
      subitem: "disabled",
      status: "default",
    },
  },
  {
    name: "colorBackgroundAlertSuccessDefault",
    value: "#EBF4EC",
    path: ["color", "background", "alert", "success", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "alert",
      subitem: "success",
      status: "default",
    },
  },
  {
    name: "colorBackgroundAlertInfoDefault",
    value: "#E8F4FD",
    path: ["color", "background", "alert", "info", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "alert",
      subitem: "info",
      status: "default",
    },
  },
  {
    name: "colorBackgroundAlertWarningDefault",
    value: "#FDF0E3",
    path: ["color", "background", "alert", "warning", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "alert",
      subitem: "warning",
      status: "default",
    },
  },
  {
    name: "colorBackgroundAlertCriticalDefault",
    value: "#FAEAEA",
    path: ["color", "background", "alert", "critical", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "alert",
      subitem: "critical",
      status: "default",
    },
  },
  {
    name: "colorBackgroundBadgeNeutralDefault",
    value: "#F5F7F9",
    path: ["color", "background", "badge", "neutral", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "badge",
      subitem: "neutral",
      status: "default",
    },
  },
  {
    name: "colorBackgroundBadgeInfoDefault",
    value: "#E8F4FD",
    path: ["color", "background", "badge", "info", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "badge",
      subitem: "info",
      status: "default",
    },
  },
  {
    name: "colorBackgroundBadgeSuccessDefault",
    value: "#EBF4EC",
    path: ["color", "background", "badge", "success", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "badge",
      subitem: "success",
      status: "default",
    },
  },
  {
    name: "colorBackgroundBadgeWarningDefault",
    value: "#FDF0E3",
    path: ["color", "background", "badge", "warning", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "badge",
      subitem: "warning",
      status: "default",
    },
  },
  {
    name: "colorBackgroundBadgeCriticalDefault",
    value: "#FAEAEA",
    path: ["color", "background", "badge", "critical", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "badge",
      subitem: "critical",
      status: "default",
    },
  },
  {
    name: "colorBackgroundBadgeDarkDefault",
    value: "#252A31",
    path: ["color", "background", "badge", "dark", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "badge",
      subitem: "dark",
      status: "default",
    },
  },
  {
    name: "colorBackgroundBadgeWhiteDefault",
    value: "#FFFFFF",
    path: ["color", "background", "badge", "white", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "badge",
      subitem: "white",
      status: "default",
    },
  },
  {
    name: "colorBackgroundServiceLogoDefault",
    value: "transparent",
    path: ["color", "background", "service", "logo", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "service",
      subitem: "logo",
      status: "default",
    },
  },
  {
    name: "colorBackgroundIllustration",
    value: "transparent",
    path: ["color", "background", "illustration"],
    attributes: {
      category: "color",
      type: "background",
      item: "illustration",
    },
  },
  {
    name: "colorBackgroundSeparator",
    value: "#EFF2F5",
    path: ["color", "background", "separator"],
    attributes: {
      category: "color",
      type: "background",
      item: "separator",
    },
  },
  {
    name: "colorBackgroundTableShadowLeft",
    value: "linear-gradient(to left, transparent, rgba(186, 199, 213, 0.23))",
    path: ["color", "background", "table", "shadow", "left"],
    attributes: {
      category: "color",
      type: "background",
      item: "table",
      subitem: "shadow",
      status: "left",
    },
  },
  {
    name: "colorBackgroundTableShadowRight",
    value: "linear-gradient(to right, transparent, rgba(186, 199, 213, 0.23))",
    path: ["color", "background", "table", "shadow", "right"],
    attributes: {
      category: "color",
      type: "background",
      item: "table",
      subitem: "shadow",
      status: "right",
    },
  },
  {
    name: "colorBackgroundTable",
    value: "#FFFFFF",
    path: ["color", "background", "table"],
    attributes: {
      category: "color",
      type: "background",
      item: "table",
    },
  },
  {
    name: "colorBackgroundTableEvenDefault",
    value: "#F5F7F9",
    path: ["color", "background", "table", "even", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "table",
      subitem: "even",
      status: "default",
    },
  },
  {
    name: "colorBackgroundTableHoverDefault",
    value: "#EFF2F5",
    path: ["color", "background", "table", "hover", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "table",
      subitem: "hover",
      status: "default",
    },
  },
  {
    name: "colorBackgroundTag",
    value: "#F5F7F9",
    path: ["color", "background", "tag"],
    attributes: {
      category: "color",
      type: "background",
      item: "tag",
    },
  },
  {
    name: "colorBackgroundTagSelectedDefault",
    value: "#252A31",
    path: ["color", "background", "tag", "selected", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "tag",
      subitem: "selected",
      status: "default",
    },
  },
  {
    name: "colorBackgroundTagHoverDefault",
    value: "#E5EAEF",
    path: ["color", "background", "tag", "hover", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "tag",
      subitem: "hover",
      status: "default",
    },
  },
  {
    name: "colorBackgroundTagSelectedHover",
    value: "#181B20",
    path: ["color", "background", "tag", "selected", "hover"],
    attributes: {
      category: "color",
      type: "background",
      item: "tag",
      subitem: "selected",
      status: "hover",
    },
  },
  {
    name: "colorBackgroundTagActiveDefault",
    value: "#D6DEE6",
    path: ["color", "background", "tag", "active", "default"],
    attributes: {
      category: "color",
      type: "background",
      item: "tag",
      subitem: "active",
      status: "default",
    },
  },
  {
    name: "colorBackgroundTagSelectedActive",
    value: "#0B0C0F",
    path: ["color", "background", "tag", "selected", "active"],
    attributes: {
      category: "color",
      type: "background",
      item: "tag",
      subitem: "selected",
      status: "active",
    },
  },
  {
    name: "colorBackgroundTooltip",
    value: "#FFFFFF",
    path: ["color", "background", "tooltip"],
    attributes: {
      category: "color",
      type: "background",
      item: "tooltip",
    },
  },
  {
    name: "colorBackgroundTooltipLargeMobile",
    value: "#005AA3",
    path: ["color", "background", "tooltip", "large", "mobile"],
    attributes: {
      category: "color",
      type: "background",
      item: "tooltip",
      subitem: "large",
      status: "mobile",
    },
  },
];
